detections:
  classes:
  - 0
  - 1
  - 2
  - 3
  - 4
  conf_threshold: 0.25
  imgsz: 640
  iou_threshold: 0.5
logging:
  backup_count: 3
  console: true
  file: false
  file_path: logs/
  level: INFO
  max_file_size: 10485760
system:
  character_model: models/yolo11s.pt
  data_path: data/test_video.mp4
  device: cuda
  license_model: models/lp_yolo11s.pt
  output_dir: output
  save: false
  tracker: bytetrack
  vehicle_model: models/detect_gtvn.pt
tracking:
  bytetrack:
    conf_threshold: 0.1
    cost_function: iou
    high_conf_iou_threshold: 0.5
    high_conf_threshold: 0.5
    low_conf_iou_threshold: 0.4
    low_conf_threshold: 0.1
    max_age: 60
    min_hits: 5
  sort:
    conf_threshold: 0.25
    cost_function: iou
    iou_threshold: 0.5
    max_age: 60
    min_hits: 5
violation:
  fps: 60
  padding: 30
  video_proof_duration: 3
